In [1]:
import numpy as np
from TMDP import TMDP
from River_swim import River

from algorithms import *
from model_functions import *

import matplotlib.pyplot as plt
import gymnasium as gym
from FrozenLake import *

#np.set_printoptions(precision=4)
import math
from utils import *

nrows = 40
nS = nrows**2
nA = 4
seed = get_current_seed()
gamma = .9
tau = 1.
#tmdp = TMDP(river, xi, tau=tau, gamma=gamma, seed=seed)
#mdp = TMDP(river, xi, tau=0., gamma=gamma, seed=seed)

env = FrozenLakeEnv(is_slippery=False, seed=seed, desc=generate_random_map(nrows))#, render_mode="human")
xi_frozen = np.ones(env.nS) * 1/env.nS
env.reset()

Current seed for result reproducibility: 66232625534188160315213425245867355021


(0, {'prob': 1})

In [2]:
tmdp = TMDP(env, xi_frozen, tau=tau, gamma=gamma, seed=seed)

In [3]:
q_c = np.zeros((nS, nA))
tmdp.update_tau(1.)
cur_res = curriculum_Q_learning(tmdp, q_c, alpha = 0.25, episodes=4000000, batch_nS=1., biased=False, lam=0., eps=.25)


Ending the loop


In [ ]:
print(cur_res["Qs"][-1])
Q = cur_res["Qs"][-1]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
from utils import *
res = {"Q":cur_res["Qs"][-1]}
json_res = to_json(res, indent=True)
write_results(nrows, nA, "FrozenLake", json_res, "w")


In [ ]:
json_res = read_results(nrows, nA, "FrozenLake")
res = from_json(json_res)
Q = np.array(res["Q"])

In [ ]:

tmdp = TMDP(env, xi_frozen, tau=0., gamma=gamma, seed=seed)
env.render_mode = "human"
tmdp.reset()
done = False
step = 0
while True:
    a = greedy(tmdp.env.s, Q, tmdp.env.allowed_actions[int(tmdp.env.s)])
    s_prime, reward, flags, prob = tmdp.step(a)
    if flags["done"]:
        tmdp.reset()
    step +=1
    if step > max(100,nrows*2):
        break

: 