In [1]:
import numpy as np
from TMDP import TMDP
from River_swim import River

from algorithms import *
from model_functions import *

import matplotlib.pyplot as plt
import gymnasium as gym
from FrozenLake import *

#np.set_printoptions(precision=4)
import math
from utils import *

nrows = 8
nS = nrows**2
nA = 4
seed = get_current_seed()
gamma = .9
tau = 1.
#tmdp = TMDP(river, xi, tau=tau, gamma=gamma, seed=seed)
#mdp = TMDP(river, xi, tau=0., gamma=gamma, seed=seed)

env = FrozenLakeEnv(is_slippery=False, seed=seed, desc=generate_random_map(nrows))#, render_mode="human")
xi_frozen = np.ones(env.nS) * 1/env.nS
env.reset()

Current seed for result reproducibility: 69946897158771257199012571247328557804


(0, {'prob': 1})

In [2]:
tmdp = TMDP(env, xi_frozen, tau=tau, gamma=gamma, seed=seed)

In [3]:
q_c = np.zeros((nS, nA))
tmdp.update_tau(.5)
cur_res = curriculum_MI(tmdp, q_c, alpha = 0.25, alpha_pol = 0.2, episodes=100000, batch_nS=1, temperature=20., biased=False, lam=1., epochs=5, dec=True)


[(0.0, 0.5), (1.0, 0.5)]
[0.0, 0.0]
Updating the policy tau_star:  0.5
[(0.0, 0.5), (1.0, 0.5)]
[0.0, 0.0]
Updating the policy tau_star:  0.5
[(0.0, 0.5), (1.0, 0.5)]
[0.0, 0.0]
Updating the policy tau_star:  0.5
[(0.0, 0.5), (1.0, 0.5)]
[0.0, 0.0]
Updating the policy tau_star:  0.5
[(0.0, 0.5), (1.0, 0.5)]
[0.0, 0.0]
Updating the policy tau_star:  0.5
[(0.0, 0.5), (1.0, 0.5)]
[0.0, 0.0]
Updating the policy tau_star:  0.5
[(0.0, 0.5), (1.0, 0.5)]
[0.0, 0.0]
Updating the policy tau_star:  0.5
[(0.0, 0.5), (1.0, 0.5)]
[0.0, 0.0]
Updating the policy tau_star:  0.5
[(0.0, 0.5), (1.0, 0.5)]
[0.0, 0.0]
Updating the policy tau_star:  0.5
[(0.0, 0.5), (1.0, 0.5)]
[0.0, 0.0]
Updating the policy tau_star:  0.5
[(0.0, 0.5), (1.0, 0.5)]
[0.0, 0.0]
Updating the policy tau_star:  0.5
[(0.0, 0.5), (1.0, 0.5)]
[0.0, 0.0]
Updating the policy tau_star:  0.5
[(0.0, 0.5), (1.0, 0.5)]
[0.0, 0.0]
Updating the policy tau_star:  0.5
[(0.0, 0.5), (1.0, 0.5)]
[0.0, 0.0]
Updating the policy tau_star:  0.5
[(0.0,

In [4]:
print(cur_res["Qs"][-1])
Q = cur_res["Qs"][-1]
print(get_softmax_policy(cur_res["thetas"][-1]))

[[ 1.38176856e-02  1.08018100e-02  2.36759172e-02  1.70362487e-02]
 [ 3.23098874e-02  1.60026301e-02  6.48746945e-03  3.80171208e-02]
 [ 1.20984818e-02  1.29206256e-04  1.18830592e-03  3.10313995e-05]
 [ 5.30858388e-03  8.92399508e-04  1.21363745e-03  4.01996011e-03]
 [-9.89782112e-04  2.83861658e-03 -2.20531570e-04 -4.96009184e-04]
 [-1.03474616e-03  9.26426700e-05  3.83169832e-04  9.71725865e-04]
 [ 7.18272648e-05  6.38862242e-04  3.77452850e-04  1.38976311e-04]
 [ 1.63407695e-05  4.01715435e-03  4.57724828e-03  1.04080379e-03]
 [ 1.37729243e-02  6.55238453e-03  4.26297395e-03  1.60200662e-02]
 [ 5.56291244e-03  6.51595572e-03  1.20468957e-03  2.14054571e-02]
 [ 1.19046671e-02 -1.36926395e-03 -2.56947592e-03 -1.76173789e-04]
 [ 1.32073882e-02  3.30591895e-03 -1.90267845e-03  7.40068050e-04]
 [ 2.84079551e-03  2.32547827e-03  2.10154409e-03  2.22359151e-03]
 [-2.14414053e-04  6.79736499e-04  1.48711590e-03  3.78910316e-04]
 [ 1.69294611e-03  3.22166261e-03  6.89886483e-04  3.07304123e

In [5]:
from utils import *
res = {"Q":cur_res["Qs"][-1], "theta":cur_res["thetas"][-1]}
json_res = to_json(res, indent=True)
write_results(nrows, nA, "FrozenLake", json_res, "w")


In [6]:
json_res = read_results(nrows, nA, "FrozenLake")
res = from_json(json_res)
pi = get_policy(get_softmax_policy(np.array(res["theta"])))
Q = np.array(res["Q"])

In [7]:
print(pi)

[[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]


In [11]:

tmdp = TMDP(env, xi_frozen, tau=0., gamma=gamma, seed=seed)
env.render_mode = "human"
tmdp.reset()
done = False
step = 0
while True:
    s = tmdp.env.s
    a = greedy(tmdp.env.s, Q, tmdp.env.allowed_actions[int(tmdp.env.s)])
    s_prime, reward, flags, prob = tmdp.step(a)
    print("state {} action {} next state {} reward {}".format(s, a, s_prime, reward))
    if flags["done"]:
        tmdp.reset()
    step +=1
    if step > max(100,nrows*2):
        break

state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2 next state 1 reward 0.0
state 0 action 2

In [9]:
tmdp.step(2)

(1, 0.0, {'done': True, 'teleport': False}, {'prob': 1.0})