In [1]:
import numpy as np
from TMDP import TMDP
from river_swim import River
import pprint

In [2]:
gamma = 0.9
river = River(gamma)
print(river.P)
#print(river.P_mat)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
state:  0 

	 action:  0 

		State:  0 prob: 1.0  reward:  5.0 

		State:  1 prob: 0.0  reward:  0.0 

		State:  2 prob: 0.0  reward:  0.0 

		State:  3 prob: 0.0  reward:  0.0 

		State:  4 prob: 0.0  reward:  0.0 

		State:  5 prob: 0.0  reward:  0.0 

	 action:  1 

		State:  0 prob: 0.7  reward:  0.0 

		State:  1 prob: 0.3  reward:  0.0 

		State:  2 prob: 0.0  reward:  0.0 

		State:  3 prob: 0.0  reward:  0.0 

		State:  4 prob: 0.0  reward:  0.0 

		State:  5 prob: 0.0  reward:  0.0 

state:  1 

	 action:  0 

		State:  0 prob: 1.0  reward:  0.0 

		State:  1 prob: 0.0  reward:  0.0 

		State:  2 prob: 0.0  reward:  0.0 

		State:  3 prob: 0.0  reward:  0.0 

		State:  4 prob: 0.0  reward:  0.0 

		State:  5 prob: 0.0  reward:  