# Stimare Q function ottimale
## 1. Quanto tempo ci mette per convergere a Q*, al variare di tau
## 2. Distanza tra Q* e Q_t 
## 3. distanza tra Q_0 e Q_0 appresa tramite i valori di tau
## 4. cercare di integrare i bound trovati

### Estrarre policy da Q
### Confrontare due diverse Q valutando diverse metriche 
### Calcolare Q*
### Tentativo di implementazione di un curriculum
### Plot functions

In [1]:
import numpy as np
from TMDP import TMDP
from river_swim import River

from algorithms import *


In [2]:
# Test with tau=0.9
nS = 8
gamma = 0.9
river = River(nS, gamma, 5, 1000)
tau = 0.9
xi = np.ones(river.nS)*1/river.nS
tmdp = TMDP(river, xi, tau, gamma)
tmdp_0 = TMDP(river, xi, 0, gamma)

In [8]:
s = tmdp.reset()
M = 10000
Q = np.zeros((tmdp.nS, tmdp.nA))
ret = 0
a = eps_greedy(s, Q, 1., tmdp.allowed_actions[s.item()])
Q = Q_learning(tmdp, s, a, Q, M)

print("\nQ function with tau: {}\n".format(tmdp.tau))
print(Q)
print(get_policy(Q))

s = tmdp_0.reset()
M_0 = 100000
Q = np.zeros((tmdp_0.nS, tmdp_0.nA))
ret = 0
a = eps_greedy(s, Q, 1., tmdp_0.allowed_actions[s.item()])
Q = Q_learning(tmdp_0, s, a, Q, M_0)


print("Q function with tau: {}".format(tmdp_0.tau))
print(Q)
print(get_policy(Q))

r_s_a = compute_r_s_a(tmdp_0.nS, tmdp_0.nA, tmdp_0.P_mat, tmdp_0.reward)
q_star = bellman_optimal_q(tmdp_0.nS, tmdp_0.nA, tmdp_0.P_mat, tmdp_0.reward, 1, gamma)


print("\n Q function with bellman operator")
print(q_star)
print(get_policy(q_star))


Q function with tau: 0

[[50.         41.88048962]
 [45.         38.21911696]
 [40.5        34.98075486]
 [36.45       32.65763077]
 [31.14259381  0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]
 [ 0.          0.        ]]
[0, 0, 0, 0, 0, 0, 0, 0]
Q function with tau: 0
[[50.         43.66722367]
 [45.         39.98912165]
 [40.5        36.4497009 ]
 [36.45       30.54654188]
 [32.805      27.55583569]
 [29.52410382 21.41201226]
 [26.08870479 21.35597274]
 [ 0.          0.        ]]
[0, 0, 0, 0, 0, 0, 0, 0]

 Q function with bellman operator
[[ 64.33978241  66.4264707 ]
 [ 59.78382363  92.64863548]
 [ 83.38377194 137.08716883]
 [123.37845195 203.98538599]
 [183.58684739 303.06311755]
 [272.75680579 449.4704471 ]
 [404.52340239 665.78575189]
 [599.2071767  985.43074649]]
[1, 1, 1, 1, 1, 1, 1, 1]


In [4]:

""" xi = np.ones(river.nS)*1/river.nS
gamma = 0.9
river = River(gamma)

for tau in taus:
    tmdp = TMDP(river, xi, tau, gamma)
    s = tmdp.reset()
    M = 10000
    Q = np.zeros((tmdp.nS, tmdp.nA))
    ret = 0
    a = eps_greedy(s, Q, 1., tmdp.allowed_actions[s.item()])
    Q = Q_learning(tmdp, s, a, Q, M)
    Qs.append({"tau":tau, "Q_function":Q, "env":tmdp})

for i in range(len(taus)):
    print("Tau:", Qs[i]['tau'])
    print(Qs[i]['Q_function']) """

' xi = np.ones(river.nS)*1/river.nS\ngamma = 0.9\nriver = River(gamma)\n\nfor tau in taus:\n    tmdp = TMDP(river, xi, tau, gamma)\n    s = tmdp.reset()\n    M = 10000\n    Q = np.zeros((tmdp.nS, tmdp.nA))\n    ret = 0\n    a = eps_greedy(s, Q, 1., tmdp.allowed_actions[s.item()])\n    Q = Q_learning(tmdp, s, a, Q, M)\n    Qs.append({"tau":tau, "Q_function":Q, "env":tmdp})\n\nfor i in range(len(taus)):\n    print("Tau:", Qs[i][\'tau\'])\n    print(Qs[i][\'Q_function\']) '

In [5]:
""" pi = get_policy(Qs[-2]['Q_function'])
pi_prime = get_policy(Qs[-1]['Q_function'])

print(pi)
print(pi_prime) """

" pi = get_policy(Qs[-2]['Q_function'])\npi_prime = get_policy(Qs[-1]['Q_function'])\n\nprint(pi)\nprint(pi_prime) "

In [10]:
taus = [1 - i*0.1 for i in range(10)]
taus.append(0)

# Curriculul for decreasing values of tau
for tau in taus:
    tmdp = TMDP(river, xi, tau, gamma)
    if tau == 1:
       Q = np.zeros((tmdp.nS, tmdp.nA))
    
    s = tmdp.reset()
    M = 10000
    ret = 0
    a = eps_greedy(s, Q, 1., tmdp.allowed_actions[s.item()])
    Q = Q_learning(tmdp, s, a, Q, M)


print("Q function learned with transfer learning:\n", Q)



Q function learned with transfer learning:
 [[  50.           44.02305276]
 [  45.           41.40971645]
 [  40.67673115   64.72405776]
 [  60.39408701  137.53374947]
 [ 125.70784313  201.07169321]
 [ 268.87396768  271.0882225 ]
 [ 325.73465883  418.2877229 ]
 [ 575.78684033 1855.71395599]]


In [11]:
pi = get_policy(Q)
print(pi)
get_expected_avg_reward(tmdp.nS, tmdp.nA, tmdp.P_mat_tau, pi, tmdp.reward, tmdp.gamma, tmdp.mu)

[0, 0, 1, 1, 1, 1, 1, 1]
[1. 0. 0. 0. 0. 0. 0. 0.]


50.000000000000014